name: howlongtobeat
description: A Flutter package to fetch game completion times from HowLongToBeat.com
publish_to: none
version: 1.0.0
homepage: https://github.com/yourusername/howlongtobeat

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
